name: Deploy from Developer to Preproduzione

on:
  push:
    branches:
      - Preproduzione

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Push changes to Produzione branch
      run: |
        git checkout -b main origin/main
        git merge --no-edit origin/Preproduzione
        git push origin main
